on:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: build

release:
  name: build
  runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Disable Spotlight
        run: sudo mdutil -a -i off

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly

      - name: "build1"
        run: "bash ./scripts/gclient.sh sync"
